interface Props {
  params: Promise<{ id: string }>;
}

export default async function Head({ params }: Props) {
  const { id } = await params;

  return (
    <>
      <title>Snapshot {id} – RepoLens</title>
      <meta
        name="description"
        content="View architecture documentation snapshot generated by RepoLens for your repository."
      />
    </>
  );
}

